FROM registry.access.redhat.com/ubi8/ubi:8.8 as java-builder
LABEL maintainer="OpsMx"

ARG JAVA_PACKAGE=java-17-openjdk-jmods
RUN yum -y update && yum -y install --nodocs ${JAVA_PACKAGE}

# Build a custom JRE.
# For now, we will include all modules.  We could try to remove the ones
# we don't need to reduce image size and security attack surface.
WORKDIR /jrebuild
RUN java --list-modules | cut -d'@' -f1 > modules
RUN jlink --output runtime --add-modules `paste -sd, - < modules` --compress 2 --vm server

# Build a minimal base image with our custom Java installed.
FROM registry.access.redhat.com/ubi8/ubi:8.8 AS java-base
LABEL maintainer="OpsMx"
COPY --from=java-builder /jrebuild/runtime /opsmx-java-runtime
ARG OPSMXUSER=1001
ENV JAVA_HOME=/opsmx-java-runtime \
    PATH=${PATH}:/opsmx-java-runtime/bin \
    WORK_DIR=/opsmx/workdir \
    CONF_DIR=/opsmx/conf

# Enabling fips mode
RUN fips-mode-setup --enable

# Setting crypto policies to FIPS
RUN update-crypto-policies --set FIPS

COPY orca-web/build/install/orca /opt/orca
#RUN yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical --setopt=tsflags=nodocs
#RUN yum -y install java-17-openjdk-devel wget vim curl net-tools nettle
RUN yum -y install wget
#RUN yum -y update
RUN useradd spinnaker
RUN mkdir -p /opt/orca/plugins

#custom plugin zip files adding
ARG CUSTOMPLUGIN_RELEASEVERSION
ENV CUSTOMPLUGIN_RELEASEVERSION=$CUSTOMPLUGIN_RELEASEVERSION

ARG CUSTOMPLUGIN_RELEASE_VERSION
ENV CUSTOMPLUGIN_RELEASE_VERSION=$CUSTOMPLUGIN_RELEASE_VERSION


RUN wget -O Opsmx.VerificationGatePlugin-VerificationPlugin-${CUSTOMPLUGIN_RELEASEVERSION}-${CUSTOMPLUGIN_RELEASE_VERSION}.zip -c https://github.com/OpsMx/Customplugins/releases/download/${CUSTOMPLUGIN_RELEASEVERSION}/VerificationPlugin-${CUSTOMPLUGIN_RELEASE_VERSION}-SNAPSHOT.zip -P /opt/orca/plugins \
   && wget -O Opsmx.TestVerificationGatePlugin-TestVerificationPlugin-${CUSTOMPLUGIN_RELEASEVERSION}-${CUSTOMPLUGIN_RELEASE_VERSION}.zip https://github.com/OpsMx/Customplugins/releases/download/${CUSTOMPLUGIN_RELEASEVERSION}/TestVerificationPlugin-${CUSTOMPLUGIN_RELEASE_VERSION}-SNAPSHOT.zip -P /opt/orca/plugins \
   && wget -O Opsmx.PolicyGatePlugin-policyPlugin-${CUSTOMPLUGIN_RELEASEVERSION}-${CUSTOMPLUGIN_RELEASE_VERSION}.zip -c  https://github.com/OpsMx/Customplugins/releases/download/${CUSTOMPLUGIN_RELEASEVERSION}/policyPlugin-${CUSTOMPLUGIN_RELEASE_VERSION}-SNAPSHOT.zip -P /opt/orca/plugins \
   && wget -O Opsmx.PolicyGatePlugin-RbacPlugin-${CUSTOMPLUGIN_RELEASEVERSION}-${CUSTOMPLUGIN_RELEASE_VERSION}.zip -c  https://github.com/OpsMx/Customplugins/releases/download/${CUSTOMPLUGIN_RELEASEVERSION}/RbacPlugin-${CUSTOMPLUGIN_RELEASE_VERSION}-SNAPSHOT.zip -P /opt/orca/plugins \
   && wget -O Opsmx.VisibilityApprovalPlugin-ApprovalStagePlugin-${CUSTOMPLUGIN_RELEASEVERSION}-${CUSTOMPLUGIN_RELEASE_VERSION}.zip -c  https://github.com/OpsMx/Customplugins/releases/download/${CUSTOMPLUGIN_RELEASEVERSION}/ApprovalStagePlugin-${CUSTOMPLUGIN_RELEASE_VERSION}-SNAPSHOT.zip -P /opt/orca/plugins

RUN mv Opsmx.VerificationGatePlugin-VerificationPlugin-${CUSTOMPLUGIN_RELEASEVERSION}-${CUSTOMPLUGIN_RELEASE_VERSION}.zip  /opt/orca/plugins/ \
    && mv Opsmx.TestVerificationGatePlugin-TestVerificationPlugin-${CUSTOMPLUGIN_RELEASEVERSION}-${CUSTOMPLUGIN_RELEASE_VERSION}.zip /opt/orca/plugins/ \
    && mv Opsmx.PolicyGatePlugin-policyPlugin-${CUSTOMPLUGIN_RELEASEVERSION}-${CUSTOMPLUGIN_RELEASE_VERSION}.zip /opt/orca/plugins/ \
    && mv Opsmx.PolicyGatePlugin-RbacPlugin-${CUSTOMPLUGIN_RELEASEVERSION}-${CUSTOMPLUGIN_RELEASE_VERSION}.zip /opt/orca/plugins/ \
    && mv Opsmx.VisibilityApprovalPlugin-ApprovalStagePlugin-${CUSTOMPLUGIN_RELEASEVERSION}-${CUSTOMPLUGIN_RELEASE_VERSION}.zip /opt/orca/plugins/



#RUN wget -O Armory.ObservabilityPlugin-armory-observability-plugin-v1.4.2-SNAPSHOT.zip -c https://github.com/OpsMx/armory-observability-plugin/releases/download/v1.0.0/armory-observability-plugin-v1.4.2-SNAPSHOT.zip -P /opt/orca/plugins 
#RUN mv Armory.ObservabilityPlugin-armory-observability-plugin-v1.4.2-SNAPSHOT.zip /opt/orca/plugins/


#custom plugin zip files adding
ARG CUSTOMPLUGIN_RELEASEORG
ENV CUSTOMPLUGIN_RELEASEORG=$CUSTOMPLUGIN_RELEASEORG

ARG CUSTOMPLUGIN_RELEASEREPO
ENV CUSTOMPLUGIN_RELEASEREPO=$CUSTOMPLUGIN_RELEASEREPO


RUN wget -O Armory.armory-observability-plugin-${CUSTOMPLUGIN_RELEASE_VERSION}-${CUSTOMPLUGIN_RELEASE_VERSION}.zip -c https://github.com/${CUSTOMPLUGIN_RELEASEORG}/${CUSTOMPLUGIN_RELEASEREPO}/releases/download/${CUSTOMPLUGIN_RELEASE_VERSION}/armory-observability-plugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip -P /opt/orca/plugins
RUN mv Armory.armory-observability-plugin-${CUSTOMPLUGIN_RELEASE_VERSION}-${CUSTOMPLUGIN_RELEASE_VERSION}.zip /opt/orca/plugins/


RUN chmod -R 777 /opt/orca/plugins/
RUN chown -R spinnaker:spinnaker /opt/
RUN yum -y remove  tar  vim vi
RUN yum -y remove clean all && rm -rf /var/cache
USER spinnaker
CMD ["/opt/orca/bin/orca"]
